### ISSUE TITLE
src/Makefile includes non-existent netmapinfo.o

### ISSUE THREAD

**Issue by nosteve** [kohler/ipsumdump#4]
Received this error after bootstrap.sh, configure, then make. Don't see reference to netmapinfo elsewhere, removing from Makefile resulted in successful build, hopefully working binary.

g++ -g -O2 -W -Wall  -o ipsumdump -rdynamic fromdagdump.o fromdevice.o fromdump.o fromipsumdump.o fromnetflowsumdump.o fromnlanrdump.o fromtcpdump.o kernelfilter.o ipsumdumpinfo.o ipsumdump_anno.o ipsumdump_icmp.o ipsumdump_ip.o ipsumdump_link.o ipsumdump_payload.o ipsumdump_tcp.o ipsumdump_udp.o toipsumdump.o todump.o anonipaddr.o changeuid.o classification.o classifier.o counter.o drivermanager.o discard.o fakepcap.o ipfilter.o ipnameinfo.o netmapinfo.o progressbar.o randomsample.o script.o switch.o tee.o timefilter.o timesortedsched.o truncateippayload.o unqueue.o ipsumdump.o sd_elements.o ../libclick-2.1/libsrc/libclick.a `../libclick-2.1/click-buildtool --otherlibs`
g++: error: netmapinfo.o: No such file or directory
make[1]: *** [ipsumdump] Error 1
make[1]: Leaving directory `/home/steve/src/ipsumdump/src'
make: *** [src] Error 2

**Comment by kohler** [comment]
Thanks, fixed in b3ecc3bc1e7429ceddf338529e1c45a15a618167.
